#' Print a Fourier descriptor object as generated by
#' \code{\link{random.fourier.descriptor}}
#' 
#' @include random-fourier.descriptor.R
#' @param fourier.descriptor A Fourier descriptor object generated by
#'   \code{\link{random.fourier.descriptor}}
#' @export
#' @examples
#' fourier.descriptor <- random.fourier.descriptor(12)
#'
#' print(fourier.descriptor)
#' @usage
#' fourier.descriptor <- random.fourier.descriptor(12)
#' 
#' print(fourier.descriptor)

print.fourier.descriptor <- function(fourier.descriptor)
{
  print('Class: fourier.descriptor')
  print(paste('Amplitude: <', paste(fourier.descriptor[['Amplitude']], collapse = ', '), '>', sep = ''))
  print(paste('Phase: <', paste(fourier.descriptor[['Phase']], collapse = ', '), '>', sep = ''))
}
